### ISSUE TITLE
README ( and therefore PyPI Page link) redirects to malware site

### ISSUE THREAD

**Issue by holdenweb** [aliang/pokerhand-eval#6]
Hi there,

I'm one of the python.org webmaster, and a site user recently reported that the link at the top of the "Algorithm" section now redirects to a malware site. I have't looked in to the reasons.

Could you please remove the offending link and refresh the PyPI release until this issue is fixed by the target domain, please?

**Comment by aliang** [comment]
Just did it

**Comment by holdenweb** [comment]
Thanks very much!

On 22 October 2015 at 07:44, Alvin Liang <notifications@github.com> wrote:

> Closed #6 <https://github.com/aliang/pokerhand-eval/issues/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aliang/pokerhand-eval/issues/6#event-442318961>.
>



-- 
Steve Holden
Developer Advocate
